# ~/.config/hypr/hypridle.conf

general {
    # Avoid starting multiple hyprlock instances simultaneously
    lock_cmd = pidof hyprlock || hyprlock       
    # Lock the screen automatically before the system goes to sleep/suspend
    before_sleep_cmd = loginctl lock-session    
    # Ensure the display wakes up properly after resuming from sleep
    after_sleep_cmd = hyprctl dispatch dpms on  
}

# Listener 1: Automatically Lock screen after 2.5 minutes (150 seconds)
listener {
    timeout = 150                                
    on-timeout = loginctl lock-session           
}

# Listener 2: Turn off the screen completely after 3 minutes (180 seconds)
listener {
    timeout = 180                                
    on-timeout = hyprctl dispatch dpms off       
    on-resume = hyprctl dispatch dpms on         
}